[toolchain]

[features]
seeds = false
skip-lint = false

[build]
target = "sbf"  # <-- This tells Anchor to use the new SBF build target instead of legacy BPF

[programs.localnet]
test_contract = "61tgd4VSLsoM53qWgdhGkMrYQeaXB7HiYSJrCPVGvjhd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/lukegullekson/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
